api = "0.7"

[buildpack]
  id = "paketo-buildpacks/cpython"
  name = "Paketo Buildpack for CPython"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/cpython/blob/main/LICENSE"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "bin/env", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    python = "3.10.x"

  [[metadata.dependencies]]
    checksum = "sha256:bf8abf002073fc73589d35015acadf5931451052ae4a84f2dea382968029e0bf"
    cpe = "cpe:2.3:a:python:python:3.10.17:*:*:*:*:*:*:*"
    deprecation_date = "2026-10-31T00:00:00Z"
    id = "python"
    licenses = ["0BSD", "CNRI-Python-GPL-Compatible", "PSF-2.0"]
    name = "Python"
    purl = "pkg:generic/python@3.10.17?checksum=8fcda0fbdc131859a4a4223abb925fd522a77e3fb3b52c46cea5f3bc2ae0cd9f&download_url=https://www.python.org/ftp/python/3.10.17/Python-3.10.17.tgz"
    source = "https://www.python.org/ftp/python/3.10.17/Python-3.10.17.tgz"
    source-checksum = "sha256:8fcda0fbdc131859a4a4223abb925fd522a77e3fb3b52c46cea5f3bc2ae0cd9f"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/python/python_3.13.5_linux_x64_bionic_f60cca3e.tgz"
    version = "3.10.17"

  [[metadata.dependencies]]
    checksum = "sha256:8fcda0fbdc131859a4a4223abb925fd522a77e3fb3b52c46cea5f3bc2ae0cd9f"
    cpe = "cpe:2.3:a:python:python:3.10.17:*:*:*:*:*:*:*"
    deprecation_date = "2026-10-31T00:00:00Z"
    id = "python"
    licenses = ["0BSD", "CNRI-Python-GPL-Compatible", "PSF-2.0"]
    name = "Python"
    purl = "pkg:generic/python@3.10.17?checksum=8fcda0fbdc131859a4a4223abb925fd522a77e3fb3b52c46cea5f3bc2ae0cd9f&download_url=https://www.python.org/ftp/python/3.10.17/Python-3.10.17.tgz"
    source = "https://www.python.org/ftp/python/3.10.17/Python-3.10.17.tgz"
    source-checksum = "sha256:8fcda0fbdc131859a4a4223abb925fd522a77e3fb3b52c46cea5f3bc2ae0cd9f"
    stacks = ["*"]
    uri = "https://www.python.org/ftp/python/3.10.17/Python-3.10.17.tgz"
    version = "3.10.17"

  [[metadata.dependencies]]
    checksum = "sha256:33e74b90423f26df117ede5563a06949ec87be18ba5f6a909e58db4ffa8aabce"
    cpe = "cpe:2.3:a:python:python:3.10.17:*:*:*:*:*:*:*"
    deprecation_date = "2026-10-31T00:00:00Z"
    id = "python"
    licenses = ["0BSD", "CNRI-Python-GPL-Compatible", "PSF-2.0"]
    name = "Python"
    purl = "pkg:generic/python@3.10.17?checksum=8fcda0fbdc131859a4a4223abb925fd522a77e3fb3b52c46cea5f3bc2ae0cd9f&download_url=https://www.python.org/ftp/python/3.10.17/Python-3.10.17.tgz"
    source = "https://www.python.org/ftp/python/3.10.17/Python-3.10.17.tgz"
    source-checksum = "sha256:8fcda0fbdc131859a4a4223abb925fd522a77e3fb3b52c46cea5f3bc2ae0cd9f"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/python/python_3.13.5_linux_x64_bionic_f60cca3e.tgz"
    version = "3.10.17"

  [[metadata.dependencies]]
    checksum = "sha256:e9c4cff84b5e242609cb0f0f4e76c85ef633c58b6837a5aa182ecbf413701fdd"
    cpe = "cpe:2.3:a:python:python:3.10.17:*:*:*:*:*:*:*"
    deprecation_date = "2026-10-31T00:00:00Z"
    id = "python"
    licenses = ["0BSD", "CNRI-Python-GPL-Compatible", "PSF-2.0"]
    name = "Python"
    purl = "pkg:generic/python@3.10.17?checksum=8fcda0fbdc131859a4a4223abb925fd522a77e3fb3b52c46cea5f3bc2ae0cd9f&download_url=https://www.python.org/ftp/python/3.10.17/Python-3.10.17.tgz"
    source = "https://www.python.org/ftp/python/3.10.17/Python-3.10.17.tgz"
    source-checksum = "sha256:8fcda0fbdc131859a4a4223abb925fd522a77e3fb3b52c46cea5f3bc2ae0cd9f"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/python/python_3.13.5_linux_x64_bionic_f60cca3e.tgz"
    version = "3.10.17"

  [[metadata.dependencies]]
    checksum = "sha256:4a5b1f1e1db24ec38adbf8143df2282d816ec070329f85a0daa1e0e0777a30cc"
    cpe = "cpe:2.3:a:python:python:3.10.18:*:*:*:*:*:*:*"
    deprecation_date = "2026-10-31T00:00:00Z"
    id = "python"
    licenses = ["0BSD", "CNRI-Python-GPL-Compatible", "PSF-2.0"]
    name = "Python"
    purl = "pkg:generic/python@3.10.18?checksum=1b19ab802518eb36a851f5ddef571862c7a31ece533109a99df6d5af0a1ceb99&download_url=https://www.python.org/ftp/python/3.10.18/Python-3.10.18.tgz"
    source = "https://www.python.org/ftp/python/3.10.18/Python-3.10.18.tgz"
    source-checksum = "sha256:1b19ab802518eb36a851f5ddef571862c7a31ece533109a99df6d5af0a1ceb99"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/python/python_3.13.5_linux_x64_bionic_f60cca3e.tgz"
    version = "3.10.18"

  [[metadata.dependencies]]
    checksum = "sha256:1b19ab802518eb36a851f5ddef571862c7a31ece533109a99df6d5af0a1ceb99"
    cpe = "cpe:2.3:a:python:python:3.10.18:*:*:*:*:*:*:*"
    deprecation_date = "2026-10-31T00:00:00Z"
    id = "python"
    licenses = ["0BSD", "CNRI-Python-GPL-Compatible", "PSF-2.0"]
    name = "Python"
    purl = "pkg:generic/python@3.10.18?checksum=1b19ab802518eb36a851f5ddef571862c7a31ece533109a99df6d5af0a1ceb99&download_url=https://www.python.org/ftp/python/3.10.18/Python-3.10.18.tgz"
    source = "https://www.python.org/ftp/python/3.10.18/Python-3.10.18.tgz"
    source-checksum = "sha256:1b19ab802518eb36a851f5ddef571862c7a31ece533109a99df6d5af0a1ceb99"
    stacks = ["*"]
    uri = "https://www.python.org/ftp/python/3.10.18/Python-3.10.18.tgz"
    version = "3.10.18"

  [[metadata.dependencies]]
    checksum = "sha256:59000323b03f97927f011b4f77f950b18b5dd3465df7229c2d7bfdf52f2cd3a2"
    cpe = "cpe:2.3:a:python:python:3.10.18:*:*:*:*:*:*:*"
    deprecation_date = "2026-10-31T00:00:00Z"
    id = "python"
    licenses = ["0BSD", "CNRI-Python-GPL-Compatible", "PSF-2.0"]
    name = "Python"
    purl = "pkg:generic/python@3.10.18?checksum=1b19ab802518eb36a851f5ddef571862c7a31ece533109a99df6d5af0a1ceb99&download_url=https://www.python.org/ftp/python/3.10.18/Python-3.10.18.tgz"
    source = "https://www.python.org/ftp/python/3.10.18/Python-3.10.18.tgz"
    source-checksum = "sha256:1b19ab802518eb36a851f5ddef571862c7a31ece533109a99df6d5af0a1ceb99"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/python/python_3.13.5_linux_x64_bionic_f60cca3e.tgz"
    version = "3.10.18"

  [[metadata.dependencies]]
    checksum = "sha256:598366c76a876590bffdc7b4bfbb28b0cb97bde0408fb05d3481364408c16269"
    cpe = "cpe:2.3:a:python:python:3.10.18:*:*:*:*:*:*:*"
    deprecation_date = "2026-10-31T00:00:00Z"
    id = "python"
    licenses = ["0BSD", "CNRI-Python-GPL-Compatible", "PSF-2.0"]
    name = "Python"
    purl = "pkg:generic/python@3.10.18?checksum=1b19ab802518eb36a851f5ddef571862c7a31ece533109a99df6d5af0a1ceb99&download_url=https://www.python.org/ftp/python/3.10.18/Python-3.10.18.tgz"
    source = "https://www.python.org/ftp/python/3.10.18/Python-3.10.18.tgz"
    source-checksum = "sha256:1b19ab802518eb36a851f5ddef571862c7a31ece533109a99df6d5af0a1ceb99"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/python/python_3.13.5_linux_x64_bionic_f60cca3e.tgz"
    version = "3.10.18"

  [[metadata.dependency-constraints]]
    constraint = "3.10.*"
    id = "python"
    patches = 2

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
