api = "0.7"

[buildpack]
  id = "paketo-buildpacks/cpython"
  name = "Paketo Buildpack for CPython"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/cpython/blob/main/LICENSE"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "bin/env", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    python = "3.10.x"

    [[metadata.dependencies]]
    checksum = "sha256:b0d3f0d0890dc49719ffee25f8cb4b5b50bc8a9235c7c2cc8a9eb2a277a5bd61"
    cpe = "cpe:2.3:a:python:python:3.10.15:*:*:*:*:*:*:*"
    deprecation_date = "2026-10-31T00:00:00Z"
    id = "python"
    licenses = ["0BSD", "CNRI-Python-GPL-Compatible", "PSF-2.0"]
    name = "Python"
    purl = "pkg:generic/python@3.10.15?checksum=a27864e5ba2a4474f8f6c58ab92ff52767ac8b66f1646923355a53fe3ef15074&download_url=https://www.python.org/ftp/python/3.10.15/Python-3.10.15.tgz"
    source = "https://www.python.org/ftp/python/3.10.15/Python-3.10.15.tgz"
    source-checksum = "sha256:a27864e5ba2a4474f8f6c58ab92ff52767ac8b66f1646923355a53fe3ef15074"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/python/python_3.10.15_linux_x64_noble_b0d3f0d0.tgz"
    version = "3.10.15"

  [[metadata.dependencies]]
    checksum = "sha256:38f7ffdc842d8781275b0ff39291cfa54b481074f9f7b892f2e64a63067407a4"
    cpe = "cpe:2.3:a:python:python:3.10.15:*:*:*:*:*:*:*"
    deprecation_date = "2026-10-31T00:00:00Z"
    id = "python"
    licenses = ["0BSD", "CNRI-Python-GPL-Compatible", "PSF-2.0"]
    name = "Python"
    purl = "pkg:generic/python@3.10.15?checksum=a27864e5ba2a4474f8f6c58ab92ff52767ac8b66f1646923355a53fe3ef15074&download_url=https://www.python.org/ftp/python/3.10.15/Python-3.10.15.tgz"
    source = "https://www.python.org/ftp/python/3.10.15/Python-3.10.15.tgz"
    source-checksum = "sha256:a27864e5ba2a4474f8f6c58ab92ff52767ac8b66f1646923355a53fe3ef15074"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/python/python_3.10.15_linux_x64_jammy_38f7ffdc.tgz"
    version = "3.10.15"

  [[metadata.dependencies]]
    checksum = "sha256:052a32b22820839c54b5c08d7ba0b08ad8f6d0d4214d69df5c7acdfc4164712a"
    cpe = "cpe:2.3:a:python:python:3.10.15:*:*:*:*:*:*:*"
    deprecation_date = "2026-10-31T00:00:00Z"
    id = "python"
    licenses = ["0BSD", "CNRI-Python-GPL-Compatible", "PSF-2.0"]
    name = "Python"
    purl = "pkg:generic/python@3.10.15?checksum=a27864e5ba2a4474f8f6c58ab92ff52767ac8b66f1646923355a53fe3ef15074&download_url=https://www.python.org/ftp/python/3.10.15/Python-3.10.15.tgz"
    source = "https://www.python.org/ftp/python/3.10.15/Python-3.10.15.tgz"
    source-checksum = "sha256:a27864e5ba2a4474f8f6c58ab92ff52767ac8b66f1646923355a53fe3ef15074"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/python/python_3.10.15_linux_x64_bionic_052a32b2.tgz"
    version = "3.10.15"

  [[metadata.dependencies]]
    checksum = "sha256:a27864e5ba2a4474f8f6c58ab92ff52767ac8b66f1646923355a53fe3ef15074"
    cpe = "cpe:2.3:a:python:python:3.10.15:*:*:*:*:*:*:*"
    deprecation_date = "2026-10-31T00:00:00Z"
    id = "python"
    licenses = ["0BSD", "CNRI-Python-GPL-Compatible", "PSF-2.0"]
    name = "Python"
    purl = "pkg:generic/python@3.10.15?checksum=a27864e5ba2a4474f8f6c58ab92ff52767ac8b66f1646923355a53fe3ef15074&download_url=https://www.python.org/ftp/python/3.10.15/Python-3.10.15.tgz"
    source = "https://www.python.org/ftp/python/3.10.15/Python-3.10.15.tgz"
    source-checksum = "sha256:a27864e5ba2a4474f8f6c58ab92ff52767ac8b66f1646923355a53fe3ef15074"
    stacks = ["*"]
    uri = "https://www.python.org/ftp/python/3.10.15/Python-3.10.15.tgz"
    version = "3.10.15"

  [[metadata.dependencies]]
    checksum = "sha256:4e06af6b0b9469ed6f206a93c36f12961e677f13f3dfd6fbfe8b3940b409e5d7"
    cpe = "cpe:2.3:a:python:python:3.10.16:*:*:*:*:*:*:*"
    deprecation_date = "2026-10-31T00:00:00Z"
    id = "python"
    licenses = ["0BSD", "CNRI-Python-GPL-Compatible", "PSF-2.0"]
    name = "Python"
    purl = "pkg:generic/python@3.10.16?checksum=f2e22ed965a93cfeb642378ed6e6cdbc127682664b24123679f3d013fafe9cd0&download_url=https://www.python.org/ftp/python/3.10.16/Python-3.10.16.tgz"
    source = "https://www.python.org/ftp/python/3.10.16/Python-3.10.16.tgz"
    source-checksum = "sha256:f2e22ed965a93cfeb642378ed6e6cdbc127682664b24123679f3d013fafe9cd0"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/python/python_3.10.16_linux_x64_noble_4e06af6b.tgz"
    version = "3.10.16"

  [[metadata.dependencies]]
    checksum = "sha256:96edafd66c86512b8e49631b50ce74333a016ab4f6472cc3d1a45d6e7bb47459"
    cpe = "cpe:2.3:a:python:python:3.10.16:*:*:*:*:*:*:*"
    deprecation_date = "2026-10-31T00:00:00Z"
    id = "python"
    licenses = ["0BSD", "CNRI-Python-GPL-Compatible", "PSF-2.0"]
    name = "Python"
    purl = "pkg:generic/python@3.10.16?checksum=f2e22ed965a93cfeb642378ed6e6cdbc127682664b24123679f3d013fafe9cd0&download_url=https://www.python.org/ftp/python/3.10.16/Python-3.10.16.tgz"
    source = "https://www.python.org/ftp/python/3.10.16/Python-3.10.16.tgz"
    source-checksum = "sha256:f2e22ed965a93cfeb642378ed6e6cdbc127682664b24123679f3d013fafe9cd0"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/python/python_3.10.16_linux_x64_jammy_96edafd6.tgz"
    version = "3.10.16"

  [[metadata.dependencies]]
    checksum = "sha256:357004dbd5fb7ba474aa11e30bc4ba90629d514236fc9fbc10fd8addb7f07302"
    cpe = "cpe:2.3:a:python:python:3.10.16:*:*:*:*:*:*:*"
    deprecation_date = "2026-10-31T00:00:00Z"
    id = "python"
    licenses = ["0BSD", "CNRI-Python-GPL-Compatible", "PSF-2.0"]
    name = "Python"
    purl = "pkg:generic/python@3.10.16?checksum=f2e22ed965a93cfeb642378ed6e6cdbc127682664b24123679f3d013fafe9cd0&download_url=https://www.python.org/ftp/python/3.10.16/Python-3.10.16.tgz"
    source = "https://www.python.org/ftp/python/3.10.16/Python-3.10.16.tgz"
    source-checksum = "sha256:f2e22ed965a93cfeb642378ed6e6cdbc127682664b24123679f3d013fafe9cd0"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/python/python_3.10.16_linux_x64_bionic_357004db.tgz"
    version = "3.10.16"

  [[metadata.dependencies]]
    checksum = "sha256:f2e22ed965a93cfeb642378ed6e6cdbc127682664b24123679f3d013fafe9cd0"
    cpe = "cpe:2.3:a:python:python:3.10.16:*:*:*:*:*:*:*"
    deprecation_date = "2026-10-31T00:00:00Z"
    id = "python"
    licenses = ["0BSD", "CNRI-Python-GPL-Compatible", "PSF-2.0"]
    name = "Python"
    purl = "pkg:generic/python@3.10.16?checksum=f2e22ed965a93cfeb642378ed6e6cdbc127682664b24123679f3d013fafe9cd0&download_url=https://www.python.org/ftp/python/3.10.16/Python-3.10.16.tgz"
    source = "https://www.python.org/ftp/python/3.10.16/Python-3.10.16.tgz"
    source-checksum = "sha256:f2e22ed965a93cfeb642378ed6e6cdbc127682664b24123679f3d013fafe9cd0"
    stacks = ["*"]
    uri = "https://www.python.org/ftp/python/3.10.16/Python-3.10.16.tgz"
    version = "3.10.16"

  [[metadata.dependency-constraints]]
    constraint = "3.10.*"
    id = "python"
    patches = 2

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
